In [1]:
import numpy as np
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [2]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [3]:
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [4]:
v = np.matrix([[2],[3],[4]])
v

matrix([[2],
        [3],
        [4]])

In [5]:
m*v

matrix([[ 8],
        [32],
        [ 2]])

In [6]:
import numpy.linalg
numpy.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [7]:
x = numpy.linalg.solve(m,v)
x

matrix([[ 0.96521739],
        [ 0.17391304],
        [ 0.46086957]])

In [8]:
m*x

matrix([[ 2.],
        [ 3.],
        [ 4.]])

In [9]:
v

matrix([[2],
        [3],
        [4]])