In [1]:
a = complex(2,4)

In [2]:
b = 3 - 5j

In [3]:
a

(2+4j)

In [4]:
b

(3-5j)

In [5]:
a.real

2.0

In [6]:
a.imag

4.0

In [8]:
a.conjugate()

(2-4j)

In [9]:
a + b

(5-1j)

In [10]:
a*b

(26+2j)

In [11]:
a/b

(-0.4117647058823529+0.6470588235294118j)

In [12]:
abs(a)

4.47213595499958

In [13]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [14]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [15]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

In [16]:
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a

array([ 2.+3.j,  4.+5.j,  6.-7.j,  8.+9.j])

In [18]:
a + 2

array([  4.+3.j,   6.+5.j,   8.-7.j,  10.+9.j])

In [19]:
np.sin(a)

array([    9.15449915  -4.16890696j,   -56.16227422 -48.50245524j,
        -153.20827755-526.47684926j,  4008.42651446-589.49948373j])

In [20]:
import math
math.sqrt(-1)

ValueError: math domain error

In [21]:
import cmath
cmath.sqrt(-1)

1j