In [1]:
x = [1,2,3,4]
y = [5,6,7,8]
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [3]:
x + y 

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])

ax*2

array([2, 4, 6, 8])

In [5]:
ax + 10

array([11, 12, 13, 14])

In [6]:
ax + ay

array([ 6,  8, 10, 12])

In [7]:
ax * ay

array([ 5, 12, 21, 32])

In [8]:
def f(x):
    return 3*x**2 - 2*x + 7

In [9]:
f(ax)

array([ 8, 15, 28, 47])

In [10]:
np.sqrt(ax)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [11]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
grid = np.zeros((10000,10000), dtype=float)

In [14]:
grid

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [15]:
grid += 10

In [16]:
grid

array([[ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       ..., 
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.]])

In [17]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ..., 
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[1]

array([5, 6, 7, 8])

In [21]:
a[:,1]

array([ 2,  6, 10])

In [22]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [23]:
a[1:3, 1:3] += 10

In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [25]:
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [26]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [28]:
np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

In [ ]:
a